#!/bin/sh

if [ -f numero_coords ]; then
	echo backspace |socat stdio unix:./sock_list
elif [ -e mpvsocket ]; then
	echo speed_set 1.0 |socat - unix:./mpvsocket
else
	echo speed_set 1.0 > fifo_cmd
fi
