#!/bin/sh

if [ -f list_coords ]; then
	echo $* |socat stdio unix:./sock_list
	exit 0
elif [ -f info_coords ] && ! [ -f stream_info ] && ! head -n 2 current|tail -n 1|grep -qP '^(Fichiers|flux/podcasts)'; then
	# On envoie la commande à info par défaut sauf si on lit un fichier ou un podcast
	echo "$*" | socat stdio unix:sock_info
	exit 0
fi

if [ -e mpvsocket ]; then
	case "$1" in
		right) echo seek 10 |socat - unix:./mpvsocket;;
		left) echo seek -10 |socat - unix:./mpvsocket;;
		up) echo seek +60 |socat - unix:./mpvsocket;;
		down) echo seek -60 |socat - unix:./mpvsocket;;
		home) echo pt_up_step 1 |socat - unix:./mpvsocket;;
	end) echo pt_up_step -1 |socat - unix:./mpvsocket;;
esac
else
	case "$1" in
		right) echo seek 10 > fifo_cmd;;
		left) echo seek -10 > fifo_cmd;;
		up) echo seek +60 > fifo_cmd;;
		down) echo seek -60 > fifo_cmd;;
		home) echo pt_up_step 1 > fifo_cmd;;
	end) echo pt_up_step -1 > fifo_cmd;;
esac
fi

