#!/bin/sh

if [ -f list_coords ]; then
	echo $* > fifo_list
	exit 0
elif [ -f info_coords ] && ! [ -f stream_info ] && ! head -n 2 current|tail -n 1|grep -q Fichiers; then
	echo "$*" > fifo_info
	exit 0
fi

case "$1" in
	right) echo seek 10 > fifo_cmd;;
	left) echo seek -10 > fifo_cmd;;
	up) echo seek +60 > fifo_cmd;;
	down) echo seek -60 > fifo_cmd;;
home) echo pt_up_step 1 > fifo_cmd;;
end) echo pt_up_step -1 > fifo_cmd;;
esac

