#!/bin/bash

# Gère l'appui sur la touche i

if [ -f info_coords ] && [ "$1" == "" ]; then
	# un bandeau d'info est actif -> on le kille
	echo clear > fifo_info
else
	ch=`head -n 1 current`,`head -n 2 current|tail -n 1`
	if [ "$ch" == "" ]; then
		serv=`head -n 3 current|tail -n 1`
		flav=`head -n 4 current|tail -n 1`
		echo name $serv $flav > fifo_list
		ch=`cat reply_list`
	fi
	echo "prog:long $ch" > fifo_info
fi

