#!/usr/bin/perl

use WWW::Mechanize;
use v5.10;
# binmode STDOUT,":utf8";

# sans paramètre affiche la liste des stations avec leur url
# passer une url en paramètre pour obtenir l'url du flux (ch = "url" dans
# la page).

my $mech = WWW::Mechanize->new();
$mech->agent_alias("Linux Mozilla");
# $mech->agent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.71 (KHTML, like Gecko) Version/6.1 Safari/537.71");
$mech->timeout(10);
my $radio = shift @ARGV || "";
$radio =~ s/^get,//;
$radio =~ s/^\/// if ($radio);
$mech->get("http://www.ecouter-en-direct.com/$radio");
$mech->save_content("page.html");
say "direct" if (!$radio);

my (%name,%rc);
if ($radio) {
	foreach (split /\n/,$mech->content) {
		if (/ch = "(.+?)"/) {
			# Just le lien extrait vers l'écoute mp3
			say "$1";
			exit(0);
		}
	}
}
foreach ($mech->links) {
	if ($_->text && $_->text !~ /^www/) {
		last if ($_->url =~ /^http/);
		say $_->text;
		say "get,",$_->url;
	}
}


