#!/usr/bin/perl

use strict;
require "http.pl";

my $str = shift @ARGV;
if ($str =~ s/^result\://) {
	print STDERR "icecast: recherche http://dir.xiph.org/search?search=$str\n";
	$_ = myget("http://dir.xiph.org/search?search=$str");
} elsif ($str) { # Catégorie par défaut
	print STDERR "icecast: categ http://dir.xiph.org/by_genre/$str\n";
	$_ = myget("http://dir.xiph.org/by_genre/$str");
} else { # Ou rien
	$_ = myget("http://dir.xiph.org/");
}
if (/encoding="(.+?)"/) {
	print "encoding: $1\n";
}
# open(F,">dump");
# print F $_;
# close(F);
print "direct\n";
print "Recherche\nRecherche\n";
print "Catégories...\nCatégories\n" if (!$str || $str =~ /result/);
my ($name,$url);
my %list = ();
my %categories = ();
my $format;
foreach (split /\n/) {
	$categories{$1}=$2 if (/by_genre\/(.+?)" title="(.+?)"/);
	if (/class="format" title="(.+?)"/) {
		$format = $1;
	} elsif (/by_format\/(.+?)"/ && $format) {
		$format = "$1 $format";
	}
	if (/href="(.+?)" title=".*?\'(.+?)\'/) {
		$name = $2;
		$url = $1;
		$list{"$name ($format)"} = "http://dir.xiph.org$url";
		$format = undef;
	}
}
if ($str eq "Catégories") {
	foreach (sort { lc($categories{$a}) cmp lc($categories{$b}) }
		keys %categories) {
		print "$categories{$_}\n$_\n";
	}
	exit 0;
}
print STDERR "liste par défaut:\n";
foreach (sort { lc($a) cmp lc($b) } keys %list) {
	print "$_\n$list{$_}\n";
}

