#!/usr/bin/perl

use strict;
use Date::Parse;
# xml::simple est vraiment obligatoire ici, format xml trop variable
use XML::Simple;
use Data::Dumper;
use WWW::Mechanize;

# Refonte complète, on abandonne podcasters qui est pourri finalement
# et on ne va garder que des résultats google pour les recherches...
#
# C'est un peu long pour un plugin mais c'est + simple que celui de youtube
# (jusqu'ici en tous cas !). En gros :
# 1ère partie : détection du type de requête à faire, exactement comme
# youtube, mais faire un module pour ça ne serait pas très pratique
# 2 - décodage du xml des podcasts avec xml::simple

my $f;
my @abo;
my $fpod = "$ENV{HOME}/.freebox/podcasts";
if (open($f,"<$fpod")) {
	@abo = <$f>;
	close($f);
	chomp @abo;
}
binmode STDERR; # ,":utf8";
binmode STDOUT, ":iso8859-15"; # ,":utf8";
my $str = shift @ARGV;
my $debug = 0; # infos
my $dump = 0;  # dump toute l'entrée ligne par ligne
$str =~ s/^result\://;
if ($str =~ /^(.+) (http.+)/) { # demande d'abonnement
	my $title = $1;
	$str = $2;
	push @abo,$title;
	push @abo,$2;
	if (open($f,">$fpod")) {
		print $f join("\n",@abo);
		close($f);
	}
}
if ($str =~ /http/ && $str !~ /^prog/) {
	print STDERR "str $str sending direct\n";
	print "direct\n";
} else {
	print STDERR "str $str sending list\n";
	print "list\n";
}
print "Recherche\nRecherche\n"; # Transmis en mode list (ne contient pas //)
print "Abonnements\n+Abonnements\n" if (@abo);
if ($str eq "Abonnements") {
	print join("\n",@abo);
	exit(0);
}
$str =~ s/ /\+/g;
my $mech = WWW::Mechanize->new();
$mech->agent_alias("Linux Mozilla");
$mech->timeout(10);
$mech->default_header('Accept-Encoding' => scalar HTTP::Message::decodable());
my ($r,$type);
if ($debug && !$str) {
	binmode STDIN; # ,":utf8";
	@_ = <>;
	$_ = join("",@_);
	$str = "http";
	print STDERR "debug mode, input from stdin\n";
} else {
	if ($str =~ /^prog.:(.+)/) {
		$mech->get($1);
	} elsif ($str && $str !~ /^http/) {
		print STDERR "requête de recherche sur $str\n"; # if ($debug);
		$mech->get("https://www.google.fr/");
		$r = $mech->submit_form(
			form_number => 1,
			fields      => {
				q => "podcast $str filetype:xml",
			}
		);
	} elsif ($str) {
		print STDERR "debug: get $str\n" if ($debug);
		$r = $mech->get($str);
	} elsif (!$str) {
		print "Podcasts Radio France\n+prog1:http://www.radiofrance.fr/espace-pro/podcast-radio-france\n";
	}
	$_ = $mech->content;
	$type = $r->header("content-type") if ($r);
	if ($str =~ /^prog1/) {
		parse_index_radio_france();
	} elsif ($str =~ /^prog2/) {
		parse_radio_france();
	}
}

my $encoding = "";

my $content = 0;
my ($link,$title,$desc,$img,$date);
print STDERR "*** type $type\n";
if (/^<\?xml/ || /^<rss xml/ || $type =~ /(application|text).xml/) {
	# Sauver le fichier pour l'information programmes (prog/podcasts.pm)
	# Normalement LWP détecte tout seul l'encodage des caractères et fait la
	# conversion (en fonction de la locale ou prend en default latin1 ?)
	# Sauf que des fois le serveur en face n'envoie pas de header avec l'
	# encodage et dans ce cas là la détection foire, et là on se retrouve
	# avec un fichier utf8 alors que normalement il est latin1.
	# On ne peut pas avoir de changement à ce niveau là, un xml est toujours
	# en utf8 sinon le parser foire, donc on sauve en désactivant explicitement
	# le décodage pour éviter tout problème.
	if ($r && open(F,">pod")) {
		print F $r->decoded_content(charset => "none");
		close(F);
	}
	s/\xe2\x80\x99/'/gs;
	s/(&[^a])/&amp;/g;
	print STDERR "décodage xml\n" if ($debug);
	# fichier xml podcast
	my $found = 0;
	foreach (@abo) {
		if ($_ eq $str) {
			$found = 1;
			last;
		}
	}
	print STDERR "trouvé abonnement\n" if ($found && $debug);

	s/\r//gm;
	my $ref = XMLin($_);
	if (!$found) {
		my $title = $ref->{channel}->{title};
		print "S'abonner\n$title $str\n";
	}

	my $item = $ref->{channel}->{item};
	# Vu que certains podcasts n'arrivent pas dans l'ordre, trie par date
	my @item = sort { my $c = $a->{pubDate}; my $d = $b->{pubDate};
	# print "avant $c et $d\n";
	if ($c !~ /^\d+$/) {
		$c =~ s/Mars/Mar/;
		$d =~ s/Mars/Mar/;
		$c = str2time($c);
		$d = str2time($d);
	}
	# print "tri $c et $d\n";
	$d <=> $c;
	} @$item;
	foreach (@item) {
		# A priori ça ne semble pas être une bonne idée de coller l'image ici
		# j'ai jamais vu ces images changer pour chaque épisode et généralement
		# elles sont assez grosses donc elles seront mieux dans le bandeau
		# d'info. Je laisse quand même le code en commentaire au cas où...
		# my $img = $_->{"media:thumbnail"}->{url};
		# print "pic:$img " if ($img && $nb++ <= 10);
		print $_->{title};
		my $date = $_->{pubDate};
		$date = str2time($date) if ($date !~ /^\d+$/);
		print " le ".get_date($date) if ($date);
		print "\n",$_->{enclosure}->{url},"\n";
	}
}

foreach ($mech->links) {
	my $u = $_->url;
	if ($u =~ /url.q=(http.+?)&/) {
		$u = $1;
		print $_->text,"\n$u\n";
		print STDERR "text: ",$_->text," url $u\n";
	}
}

sub get_date {
	my $time = shift;
	my ($sec,$min,$hour,$mday,$mon,$year) = localtime($time);
	sprintf("%d/%02d/%02d, %02d:%02d",$mday,$mon+1,$year+1900,$hour,$min);
}

sub parse_index_radio_france {
	s/\r//g;
	s/\n//g;
	while (s/^.+?<a title="([^"]+)" href="(http[^"]+)" target="_blank"><img class="img-float-left" src="([^"]+)"//) {
		print "pic:http://www.radiofrance.fr$3 $1\n+prog2:$2\n";
	}
	exit(0);
}

sub parse_radio_france {
	s/\r//g;
	s/\n//g;
	while (s/^.+?<div class="index">//) {
		s/([\dh]+)//;
		my $heure = $1;
		s/<img src="(.+?)" alt="(.+?)"//;
		print "pic:$1 $heure : $2\n";
		s/<a href="(http.+?)" title="Abonnement par RSS"//;
		print "$1\n";

	}
	exit(0);
}
