#!/usr/bin/perl

# Navigation du site www.shoutcast.com

use strict;
use LWP::UserAgent;

sub get_url {
	my $url = shift;
	my $post = shift;
	my $useragt = 'Telerama/1.0 CFNetwork/445.6 Darwin/10.0.0d3';
	my $browser = LWP::UserAgent->new(keep_alive => 0,
		agent =>$useragt);
	$browser->timeout(10);
	$browser->default_header(
		[ 'Accept-Language' => "fr-fr"
			#                          'Accept-Encoding' => "gzip,deflate",
			# 'Accept-Charset' => "ISO-8859-15,utf-8"
		]
	);

	$browser->max_size(65000);
	my $response;
    if (!$post) {
		$response = $browser->get($url);
	} else {
		$response = $browser->post($url,$post);
	}

	return undef if (!$response->is_success);
	return undef if ($response->header("Content-type") !~ /text/);
	$response->content;
}

my $arg = shift @ARGV;
if (!$arg) {
	my $page = get_url("http://www.shoutcast.com/");
	if ($page =~ /encoding="(.+?)"/) {
		print "encoding: $1\n";
	}
	print "list\n";
	print "Recherche\nRecherche\n";
	while ($page =~ s/class="arrowup".+?href="(.+?)">(.+?)<//) {
		my ($link,$name) = ($1,$2);
		$link =~ s/\/radio\///;
		print "$name\n";
		print "$link\n";
	}
	exit 0;
}

# Ici on a un argument de genre. On pourrait aller chercher les sous genres
# mais ça m'obligerait à faire un affichage à 2 colonnes, ça deviendrait
# compliqué à programmer et à utiliser. On va se contenter des genres de base
# de toutes façons on a tendance à retrouver des stations dans pas mal de genres
# déjà.
# Par contre on va utiliser leur script ajax pour avoir les stations c'est +
# souple que la page html de base qui ne les donne que par 10.

my $page;
if ($arg =~ /^result\:(.+)/) {
	my $str = $1;
    $str =~ s/ /%20/g;
    $page = get_url("http://www.shoutcast.com/Internet-Radio/$str");
} else {
    $page = get_url("http://www.shoutcast.com/genre-ajax/$arg",{
	    count => 50,
	    ajax => "true",
	    mode => "listeners",
	    order => "desc",});
}
if ($page =~ /encoding="(.+?)"/) {
	print "encoding: $1\n";
}
print "direct\n";

while ($page =~ s/<a href="(.+?)".+?name="(.+?)"//) {
    my ($url,$name) = ($1,$2);
    if ($url =~ /pls/) {
	# A priori les liens shoutcast sont tous en pls
	# la regex pour identifier les liens est trop large
	print "$name\n$url\n";
    }
}

